title: "Luís Felipe Bilecki"
description: "Portfólio profissional de Luís Felipe Bilecki"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

url: ""
baseurl: ""

author:
  name: "Luís Felipe Bilecki"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/luisbilecki"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/luisbilecki/"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-gist

markdown: kramdown

sass:
  quiet_deps: true
  silence_deprecations: ["import"]
